alias python=python3
alias cpc="xclip -sel c < "
alias vif='vim $(fd --hidden | fzf)'
alias wgu='wg-quick up wg0'
alias wgd='wg-quick down wg0'
alias wgs='sudo wg show'
alias rgf='vim $(rg . -n | fzf --print0 -e| grep "^.*\.md" -o -a)' #fuzzy full text search
alias cda='cd ~/code/athenist-project/athenist'
alias cdo='cd ~/code/athenist-project/athenist'
alias cdw='cd ~/code/chrislco/content/writing'
alias style='cd ~/styles/style'
alias bat='batcat'
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bashrc'
alias vw='vim ~/code/chrislco/content/vw.md -c "ALEDisable" -c "Prose"'
alias ..="cd .."
alias ga='git add'
alias gs='git status'
alias gsu='git status -uno'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git push'
alias gd='git diff'
alias gp='git log --oneline --graph --decorate --all'
alias gpt='vim  -c "AIChat" chat.md'
alias wifi='nmtui'
alias lynx='lynx -vikeys'
alias fd='fdfind'

